audio:
  exports:
    for_flame:
  imports:
  styleframes:
  scripts:
    test:
    new:
  session_bkups:
colour:
  baselight_archive:
  for_flame:
    graded_media:
    proxies:
    ungraded_media:
  luts:
  media:
  refs:
  renders:
    approvals:
    finals:
  scene_archive:
docs:
  production_docs:
  storyboards:
  treatment:
edits:
  conform_lists:
  offline_refs:
vfx:
  tools:
    houdini:
      otls:
      shelves:
    nuke:
      gizmos:
  build:
    user:
  export:
    data:
    footage:
    for_colour:
    outsource:
    stills:
    wips:
  flame_archive:
    assist_archives:
    main_archive:
  import:
    artwork:
    data:
    fonts:
    docs:
      production_docs:
      storyboards:
      treatment:
    footage:
    outsource:
    stills:
    stock:
      purchased:
      watermarked:
  internal_dailies:
  published_elements:
    build:
    pre:
    seq:
  shoot:
    docs:
    hdri:
    scans:
    stills:
  appdata:
    flipbook:
    deadline:
    ingested_tracking:

