audio:
  exports:
    for_flame:
  imports:
  styleframes:
  scripts:
    test:
    new:
  session_bkups:
colour:
  baselight_archive:
  for_flame:
    graded_media:
    proxies:
    ungraded_media:
  luts:
  media:
  refs:
  renders:
    approvals:
    finals:
  scene_archive:
docs:
  production_docs:
  storyboards:
  treatment:
edits:
  conform_lists:
  offline_refs:
vfx:
  build:
    user:
  export:
    deliveries:
    reviews_client:
      from_mcr:
    reviews_internal:
      for_assists:
    data:
  import:
    artwork:
    data:
    fonts:
    turnover:
  published_elements:
    build:
    pre:
    seq:
  seq:
  shoot:
    docs:
    hdri:
    scans:
    stills:
  tools:
    houdini:
    nuke:
  appdata:
    flipbook:
    deadline:
    ingested_tracking:

