maya:
  abc:
  assets:
  cache:
  clips:
  data:
  images:
  movies:
  render:
  renderData:
  sceneAssembly:
  scenes:
  scripts:
  sounds:
  sourceimages:
nuke:
  render:
  scripts:
  stills:
unreal:
  render:
  cache:
blender:
  scenes:

