houdini:
  abc:
  archive:
  audio:
  backup:
  cache:
  geo:
  hda:
  hip:
  otls:
  render:
  renderPublish:
  scripts:
  sim:
  tex:
  video:
maya:
  abc:
  assets:
  cache:
  clips:
  data:
  images:
  movies:
  render:
  renderData:
  renderPublish:
  sceneAssembly:
  scenes:
  scripts:
  sounds:
  sourceimages:
nuke:
  render:
  scripts:
  stills:
unreal:
  render:
  cache:
blender:
  abc:
  cache:
  scenes:
